on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: rumblefrog/setup-sp@v1.0.0

      - run: |
          mkdir -p addons/sourcemod/plugins include

          cp -r scripting gamedata addons/sourcemod/

          curl -o include/dhooks.inc \
            https://raw.githubusercontent.com/peace-maker/DHooks2/dynhooks/sourcemod/scripting/include/dhooks.inc
          curl -o include/updater.inc \
            https://bitbucket.org/GoD_Tony/updater/raw/default/include/updater.inc

          spcomp \
            -i include \
            addons/sourcemod/scripting/tf2-passtime-tweaks.sp \
            -o addons/sourcemod/plugins/tf2-passtime-tweaks.smx

          zip tf2-passtime-tweaks $(find addons -type f)

          cp updatefile.txt addons/sourcemod/

      - uses: actions/create-release@latest
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tf2-passtime-tweaks.zip
          asset_name: tf2-passtime-tweaks.zip
          asset_content_type: application/zip

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: updater
          publish_dir: addons/sourcemod
